version: '3.8'
services:
  observer:
    build: .
    container_name: se_server_observer
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "main.py"]
    environment:
      - PYTHONUNBUFFERED=1
    # ports, depends_on, etc. can be added as needed for InfluxDB, Grafana
