apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
    secureJsonData:
      token: ${INFLUXDB_TOKEN}

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${POSTGRES_USER}
    database: ${POSTGRES_DB}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: false
